seed: 42
FOLD_SIZE: 3000
NUM_TOP_PROBLEMS: 10

DATA_DIR: '/data/ephemeral/input/data/train/'
data: 'train_ratings.csv'

# device: False
batch_size: 126
corruption_ratio: 0.5
num_hidden_units: 250
n_epochs: 80
learning_rate: 0.001
